hmrc/currency-conversion

- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
> PAS-835: Dependencies updated

- project/AppDependencies.scala
- project/TestPhases.scala
- project/build.properties
Upgrade to Scala 2.12.12 and sbt 1.3.13
> [PAS-905]: Upgrade to Scala 2.12.12 and sbt 1.3.13

- conf/resources/xml/exrates-monthly-1020.xml
Updated Exchange rate for October 2020
> [PAS-963][PR]: Updated Exchange rate for October 2020

- conf/resources/xml/exrates-monthly-1020.xml
Fixed the &amp issue in the xml file
> [PAS-963][PR]: Updated Exchange rates for Oct 2020

- conf/resources/xml/exrates-monthly-1120.xml
Added Nov 2020 exchange rates xml
> [PAS-1045][PR]:Added Nov 2020 exchange rates xml

- conf/resources/xml/exrates-monthly-1220.XML
PAS-1101: Dec 2020 Currency file upload
> PAS-1101: Dec 2020 Currency file upload

- README.md
- conf/resources/xml/exrates-monthly-0121.xml
Added Exchange rate file for Jan 2021
> [PR][PAS-1175]: Exchange rate file for Jan 2021

- app/uk/gov/hmrc/currencyconversion/binders/DateBinder.scala
- app/uk/gov/hmrc/currencyconversion/controllers/ExchangeRateController.scala
- app/uk/gov/hmrc/currencyconversion/models/ConversionRatePeriod.scala
- app/uk/gov/hmrc/currencyconversion/models/Currency.scala
- app/uk/gov/hmrc/currencyconversion/models/ExchangeRateResult.scala
- app/uk/gov/hmrc/currencyconversion/repositories/ConversionRatePeriodRepository.scala
- app/uk/gov/hmrc/currencyconversion/services/ExchangeRateService.scala
- app/uk/gov/hmrc/currencyconversion/utils/CurrencyParsing.scala
- app/uk/gov/hmrc/currencyconversion/utils/ExchangeRateParsing.scala
- conf/application.conf
- test/uk/gov/hmrc/currencyconversion/binders/BinderSpec.scala
- test/uk/gov/hmrc/currencyconversion/controllers/ExchangeRateControllerSpec.scala
- test/uk/gov/hmrc/currencyconversion/repositories/ExchangeRateRepositorySpec.scala
- test/uk/gov/hmrc/currencyconversion/utils/CurrencyParsingSpec.scala
- test/uk/gov/hmrc/currencyconversion/utils/ExchangeRateParsingSpec.scala
Fix copyright issues for currency-conversion.
> PAS-1200: Fix copyright for 2021-currency-conversion

- conf/resources/xml/exrates-monthly-0221.xml
1. Exchange rates' file added for Feb, 2021.
2. This can be deployed to production without any issue.
> PAS-1176: Exchange Rate update for Feb2021

- conf/resources/xml/exrates-monthly-0521.xml
1. Exchange Rate update to May2021 in DEV and PROD.
2. Link to AT >> https://github.com/hmrc/bc-passengers-acceptance-tests/pull/233
> PAS-1262: Exchange Rate update to May2021 in DEV and PROD

- conf/resources/xml/exrates-monthly-0621.xml
Currency conversion file added for June month
> PAS-1381: Update Exchange Rates for June 2021

- app/uk/gov/hmrc/currencyconversion/connectors/HODConnector.scala
> PAS-ENV-change : change enviormnet header

- app/uk/gov/hmrc/currencyconversion/connectors/HODConnector.scala
Change the response body into empty
> PAs-eis-fix : Change the response body into empty

- app/uk/gov/hmrc/currencyconversion/connectors/HODConnector.scala
> PAS-eis_JsonChange : Emtpy json chages

- conf/resources/xml/exrates-monthly-0721.xml
PAS-1408
- Update Exchange Rates for July 2021
> PAS-1408: Update Exchange Rates for July 2021

- app/uk/gov/hmrc/currencyconversion/controllers/ExchangeRateController.scala
- app/uk/gov/hmrc/currencyconversion/repositories/ExchangeRateRepository.scala
- app/uk/gov/hmrc/currencyconversion/workers/XrsExchangeRateRequestWorker.scala
> PAS-1364: Alert on XRS Errors

- app/uk/gov/hmrc/currencyconversion/repositories/ExchangeRateRepository.scala
> PAS : Fixing date issue in Currency service

- app/uk/gov/hmrc/currencyconversion/connectors/HODConnector.scala
- app/uk/gov/hmrc/currencyconversion/controllers/ExchangeRateController.scala
- app/uk/gov/hmrc/currencyconversion/repositories/ConversionRatePeriodJson.scala
- app/uk/gov/hmrc/currencyconversion/repositories/ExchangeRateRepository.scala
- app/uk/gov/hmrc/currencyconversion/workers/XrsExchangeRateRequestWorker.scala
- build.sbt
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/uk/gov/hmrc/currencyconversion/binders/BinderSpec.scala
- test/uk/gov/hmrc/currencyconversion/connectors/HODConnectorSpec.scala
- test/uk/gov/hmrc/currencyconversion/controllers/ExchangeRateControllerSpec.scala
- test/uk/gov/hmrc/currencyconversion/workers/XrsExchangeRateRequestWorkerSpec.scala
Bootstrap and Test Library upgrades
No AT/PT required
> PAS-1450 Bootstrap and Test library upgrade

- app/uk/gov/hmrc/currencyconversion/connectors/HODConnector.scala
- app/uk/gov/hmrc/currencyconversion/models/ExchangeRateObject.scala
- app/uk/gov/hmrc/currencyconversion/repositories/ConversionRatePeriodJson.scala
- app/uk/gov/hmrc/currencyconversion/repositories/ExchangeRateRepository.scala
- app/uk/gov/hmrc/currencyconversion/workers/XrsExchangeRateRequestWorker.scala
- conf/application.conf
- project/AppDependencies.scala
- test/uk/gov/hmrc/currencyconversion/binders/BinderSpec.scala
- test/uk/gov/hmrc/currencyconversion/connectors/HODConnectorSpec.scala
- test/uk/gov/hmrc/currencyconversion/controllers/ExchangeRateControllerSpec.scala
- test/uk/gov/hmrc/currencyconversion/utils/WireMockHelper.scala
- test/uk/gov/hmrc/currencyconversion/workers/XrsExchangeRateRequestWorkerSpec.scala
> PAS-1447 : Mongo Migration

- app/uk/gov/hmrc/currencyconversion/repositories/ExchangeRateRepository.scala
- test/uk/gov/hmrc/currencyconversion/controllers/ExchangeRateControllerSpec.scala
> PAS-1422 : AT fix for currency conversion

- app/uk/gov/hmrc/currencyconversion/repositories/ExchangeRateRepository.scala
PAS-1422 : Mongo upgrade log correction
> PAS-1422 : Mongo upgrade log correction

- app/uk/gov/hmrc/currencyconversion/models/ExchangeRate.scala
- app/uk/gov/hmrc/currencyconversion/workers/XrsDelayHelper.scala
- app/uk/gov/hmrc/currencyconversion/workers/XrsExchangeRateRequestWorker.scala
- build.sbt
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/uk/gov/hmrc/currencyconversion/workers/XrsDelayHelperSpec.scala
- test/uk/gov/hmrc/currencyconversion/workers/XrsExchangeRateRequestWorkerSpec.scala
Add logging to check the Exchange data size we receive.
> DDCE-2748 - Improve logging around the currency-conversion monthly worker

- .scalafmt.conf
- app/uk/gov/hmrc/currencyconversion/binders/DateBinder.scala
- app/uk/gov/hmrc/currencyconversion/config/DesCircuitBreakerProvider.scala
- app/uk/gov/hmrc/currencyconversion/config/HmrcModule.scala
- app/uk/gov/hmrc/currencyconversion/connectors/HODConnector.scala
- app/uk/gov/hmrc/currencyconversion/controllers/ExchangeRateController.scala
- app/uk/gov/hmrc/currencyconversion/models/ConversionRatePeriod.scala
- app/uk/gov/hmrc/currencyconversion/models/ExchangeRate.scala
- app/uk/gov/hmrc/currencyconversion/models/ExchangeRateObject.scala
- app/uk/gov/hmrc/currencyconversion/models/Service.scala
- app/uk/gov/hmrc/currencyconversion/repositories/ConversionRatePeriodJson.scala
- app/uk/gov/hmrc/currencyconversion/repositories/ExchangeRateRepository.scala
- app/uk/gov/hmrc/currencyconversion/services/ExchangeRateService.scala
- app/uk/gov/hmrc/currencyconversion/workers/XrsDelayHelper.scala
- app/uk/gov/hmrc/currencyconversion/workers/XrsExchangeRateRequestWorker.scala
- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
- run_all_tests.sh
- scalastyle-config.xml
- test/uk/gov/hmrc/currencyconversion/binders/BinderSpec.scala
- test/uk/gov/hmrc/currencyconversion/connectors/HODConnectorSpec.scala
- test/uk/gov/hmrc/currencyconversion/controllers/ExchangeRateControllerSpec.scala
- test/uk/gov/hmrc/currencyconversion/workers/XrsDelayHelperSpec.scala
- test/uk/gov/hmrc/currencyconversion/workers/XrsExchangeRateRequestWorkerSpec.scala
> DDCE-2636 - sbt, scalafmt + scalastyle

- app/uk/gov/hmrc/currencyconversion/controllers/ExchangeRateController.scala
- app/uk/gov/hmrc/currencyconversion/models/ExchangeRateResult.scala
- app/uk/gov/hmrc/currencyconversion/repositories/ConversionRatePeriodJson.scala
- app/uk/gov/hmrc/currencyconversion/repositories/ConversionRatePeriodRepository.scala
- app/uk/gov/hmrc/currencyconversion/repositories/ExchangeRateRepository.scala
- app/uk/gov/hmrc/currencyconversion/services/ExchangeRateService.scala
- app/uk/gov/hmrc/currencyconversion/workers/XrsExchangeRateRequestWorker.scala
- conf/application.conf
- test/uk/gov/hmrc/currencyconversion/controllers/ExchangeRateControllerSpec.scala
- test/uk/gov/hmrc/currencyconversion/repositories/ConversionRatePeriodJsonSpec.scala
- test/uk/gov/hmrc/currencyconversion/repositories/DefaultExchangeRateRepositorySpec.scala
- test/uk/gov/hmrc/currencyconversion/services/ExchangeRateServiceSpec.scala
> DDCE-4292: implement fallback mechanism for configurable number of months
